import sys

from .patch import create_patched_apk

sys.exit(create_patched_apk(
    "com.google.android.youtube",
    {
        "Announcements",
        "Alternative thumbnails",
        "Change start page",
        "Client spoof",
        "Copy video URL",
        "Custom branding",
        "Disable fullscreen ambient mode",
        "Disable resuming Shorts on startup",
        "Enable slide to seek",
        "Hide Shorts components",
        "External downloads",
        "Hide ads",
        "Hide breaking news shelf",
        "Hide cast button",
        "Hide email address",
        "Hide floating microphone button",
        "Hide player buttons",
        "Hide video action buttons",
        "Hide watermark",
        "Minimized playback",
        "Navigation buttons",
        "Open links externally",
        "Player flyout menu",
        "Remember video quality",
        "Remove tracking query parameter",
        "Restore old seekbar thumbnails",
        "Restore old video quality menu",
        "Return YouTube Dislike",
        "SponsorBlock",
        "Spoof app version",
        "Swipe controls",
        "Theme",
        "GmsCore support",
        "Video ads",
        "Playback speed",
        "Bypass URL redirects",
    },
))
